name: test-caching-npm
on: 
  workflow_dispatch: 
    inputs: 
      cache: 
        type: boolean
        description: Do you want cache
        default: true
      node-version: 
        type: choice
        description: Enter the node veraion
        default: 18.x
        options: 
          - 14.x
          - 18.x
          - 20.x
jobs: 
  build: 
    defaults: 
      run: 
        working-directory: 13-caching/react-app
    runs-on: ubuntu-latest
    outputs: 
      cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v3
        with:  
          node-version: '${{ inputs.node-version }}'
      - name: print cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('package-lock.json') }}" >> "$GITHUB_OUTPUT"
      - name: caching the dependencies
        uses: actions/cache@v3
        if: inputs.cache
        with: 
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit !=true
        run: npm ci
      - name: Testing
        run: npm run test
      - name: initiate build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: my-repo
          path: 13-caching/react-app/node_modules
          
        


    



